version: '3.9'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.Client
    container_name: merntest-client
    ports:
      - "3000:3000"   

  server:
    build:
      context: .
      dockerfile: Dockerfile.Server
    container_name: merntest-server
    ports:
      - "3001:3001"   

  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile.Server
  #   ports:
  #     - "3001:3001"   
