name: deploy
on: [push]

env:
  SERVICE: server
  REGION: us-east-1


jobs:
  deploy-server:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'


    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: server
        push: false
        tags: user/app:latest



    - name: Deploy to Cloud Run
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        project: ${{secrets.PROJECT_ID}}
        service: 'server'
        image: 'docker.io/library/user/app:latest'

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
