name: deploy
on: [push]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: server
  REGION: us-east-1


jobs:
  deploy-server:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'


    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Build and Push Container
      run: |-
        docker build -t mern-server:latest ./server
        docker push mern-server:latest

    - name: Deploy to Cloud Run
      working-directory: server
      run: |-
        gcloud run deploy ${{ env.SERVICE }} \
          --region ${{ env.REGION }} \
          --image mern-server:latest \
          --platform "managed" \
          --quiet